### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by orefalo** [theetherGit/EtherCare#1]
I can't get this code to work.

duplicate login routes - fixed
"redis" module missing - fixed
uses port 80 - fixed

yet, it doesn't work...

**Comment by theetherGit** [comment]
About uses port 80 that's a personal choice. I need to push new changes but logout doen't work

**Comment by orefalo** [comment]
I realize, plz consider that on unix system any port <1024 is for root only.

**Comment by theetherGit** [comment]
I'll remember that for future. Between all the login and logout issues are fixed you can try it now all the authentication and authorization works perfectly.

**Comment by orefalo** [comment]
thank you

I get two errors 
"redis" dependency not found
and pnpm also complains about a missing peer dep "postcss"


the port you already know about - pick 8080, or better, let sveltekit pick it for you - don't set it

**Comment by theetherGit** [comment]
Happy to help

For redis you have to setup a redis-stack-server to use this [Redis-stack-node](https://github.com/redis/redis-om-node).
Redis-stack is a primary db like postgress you can learn about it on [redis.io](https://redis.io/docs/stack/get-started/install/). So setup this and then try to use it.

"postcss" issue i didn't found it can you please share more details on that??

For port, i have configured a specific domain name for my lan network and i use static ip so to avoid port issue i use 80, so i just go to "dev.server" in browser instead of "ip:port". I hope you will understand that. But after completing this whole project i'll update the port detail.

**Comment by theetherGit** [comment]
Steps to run this project:
1. Setup redis stack server not just redis.
2. If you have any problem related to port then please configure it in vite config.
3. then npm/pnpm to install dependencies.

If you find any other please open a ticket i'll be happy to help you.

**Comment by theetherGit** [comment]
@orefalo I'm closing this as all the requirements and patches are pushed to main repo.

**Comment by orefalo** [comment]
thank you

**Comment by orefalo** [comment]
Error: Cannot find module 'redis' imported from '/..../svelte-related/EtherCare/src/lib/Redis/dbClient.ts'

 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

.
├─┬ autoprefixer 10.4.12
│ └── ✕ missing peer postcss@^8.1.0
└─┬ svelte-check 2.9.1
  └─┬ svelte-preprocess 4.10.7
    └── ✕ missing peer postcss@"^7 || ^8"
Peer dependencies that should be installed:

**Comment by orefalo** [comment]
When you provide an example, the idea is to make it as smooth as possible for the developers reviewing your code. Not every one is a Svelte/Redit/PostCss expect and getting working example drafts the line between great and unless.

just trying to help

PS: Also you are not using the default REDIS port - which will be an issue and require knowledge and touch up.
...and instructions to start Redis

**Comment by theetherGit** [comment]
Ok I'll keep that in mind and try to make it a better project for everyone.
